### ISSUE TITLE
How to reduce the volume of data collected?

### ISSUE THREAD

**Issue by madtechsupport** [logentries/docker-logentries#18]
Hi,

We're getting 100+ GB of data a week, it's too much for our Logentries plan. How can we reduce the number of stats collected?

What about including an option to change the frequency of reporting the stats?

Regards,

Warren.

**Comment by mcollina** [comment]
You might want to test https://github.com/nearform/docker-logentries/pull/16 and also use stats only when needed.

**Comment by mihaidma** [comment]
I made a PR for a downsampling feature that will let you reduce the number of stats. The parameter added is ``` -i | --statsinterval``` parameter. This collects the number of logs you specified and outputs their average value.

**Comment by StephenHynes7** [comment]
This should be available in the latest container.
