### ISSUE TITLE
Only stats are being logged 

### ISSUE THREAD

**Issue by l15k4** [logentries/docker-logentries#27]
Hey, when I do what documentation says : 

1) run an ubuntu container `docker run -t -i ubuntu:14.04 /bin/bash`
2) `docker run -v /var/run/docker.sock:/var/run/docker.sock logentries/docker-logentries -t <token> -j -a host=uname -n`
3) echo "some log entry from ubuntu container"

then `docker logs ubuntu_container` yeilds the echos but logentries Live Tail only yields the docker stats, but no entries at all, no matter what I do I cannot make it log any docker logs ... If I use `--no-stats` flag then nothing is logged at all

`Docker version 1.7.1, build 786b29d`

**Comment by l15k4** [comment]
Imho the reason is this : 
https://github.com/mcollina/docker-loghose/issues/2

**Comment by mihaidma** [comment]
I made some fixes and also added some new feature(s) one week ago: -l <LOGSTOKEN> -k <STATSTOKEN> -e <EVENTSTOKEN>
With each of the params you can log a different type of info, -t logs all of them.
Tested with the sample app, cli and also docker. I think it should work also for your use case.

**Comment by l15k4** [comment]
Thank you, I'll test it by the end of the next week and let you know

**Comment by l15k4** [comment]
@mihaidma I finally see them nasty logs, thanks !
