### ISSUE TITLE
Doesn't work with docker-compose?

### ISSUE THREAD

**Issue by beorn** [logentries/docker-logentries#30]
For some reason, I can't get this to work as part of a docker-compose.yml file:

    logentries:
      image: logentries/docker-logentries
      volumes:
       - "/var/run/docker.sock:/tmp/docker.sock"
      command: -t mytokenhere -j -a host=myhosthere

It returns:

    logentries_1 | events.js:85
    logentries_1 |       throw er; // Unhandled 'error' event
    logentries_1 |             ^
    logentries_1 | Error: connect ENOENT
    logentries_1 |     at exports._errnoException (util.js:746:11)
    logentries_1 |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
    logentries_1 exited with code 1

**Comment by Anthonyzou** [comment]
I don't think there should be quotes on the volumes part and the path is wrong.

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

**Comment by beorn** [comment]
That works!  The quotes are okay, but I had the wrong path.

**Comment by vaidas-lungis** [comment]
Is there any possibility to hide your token using docker-compose or use from file? I want to commit docker-compose.yml file.
